Repository hyeonji1125/sfacspace-06-project, pull requests merged in 2024-08, with the labels that each got.

#2 design: Header, Footer UI
  package-lock.json
  package.json
  public/next.svg
  public/vercel.svg
  src/app/assets/icons.ts
  src/app/assets/images/flaw-detector-main-logo.png
  src/app/assets/images/footer-dark-sfac-logo.png
  src/app/assets/images/footer-pattern.png
  src/app/assets/svg/SvgIcons.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/store/useDarkModeStore.ts
  src/app/types/index.d.ts
  src/app/types/utils.ts
  tailwind.config.ts
Labels: 🎨CSS

#4 [#3] feat: 디렉토리 구조 수정 + 이미지 파일 수정 + 빌드 오류 수정 + Floating 버튼 구현
  package-lock.json
  package.json
  public/assets/icons.ts
  public/assets/images/flaw-detector-main-logo.svg
  public/assets/images/footer-pattern.svg
  public/assets/images/footer-sfacspace-logo.svg
  public/assets/svg/SvgIcons.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/AskButton.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/TopButton.tsx
  src/store/useDarkModeStore.ts
  src/store/useVisibilityStore.ts
  src/styles/globals.css
  src/types/index.d.ts
  src/types/utils.ts
  tailwind.config.ts
Labels: 🤬BugFix, 🌟Feature, ⚙Setting

#5 main 배포 test
  package-lock.json
  package.json
  public/assets/icons.ts
  public/assets/images/flaw-detector-main-logo.svg
  public/assets/images/footer-pattern.svg
  public/assets/images/footer-sfacspace-logo.svg
  public/assets/svg/SvgIcons.tsx
  public/next.svg
  public/vercel.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/AskButton.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/TopButton.tsx
  src/store/useDarkModeStore.ts
  src/store/useVisibilityStore.ts
  src/styles/globals.css
  src/types/index.d.ts
  src/types/utils.ts
  tailwind.config.ts
Labels: 🖥Deploy, ✅Test

#15 [#11] style:header 로고 폰트 적용, footer 수정
  .github/ISSUE_TEMPLATE/🌟-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/AskButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/TopButton.tsx
  src/styles/globals.css
  src/types/utils.ts
Labels: 🎨CSS

#16 [#7] feat: 공통 input 컴포넌트 생성
  src/components/common/Input.tsx
  src/components/common/Textarea.tsx
  tailwind.config.ts
Labels: 🎨CSS

#18 [#17] feat: 공통 팝업(모달) 컴포넌트 생성
  src/app/layout.tsx
  src/components/common/Modal.tsx
  tailwind.config.ts
Labels: 🎨CSS

#20 [#10] feat: Dropdown 컴포넌트 제작
  package-lock.json
  package.json
  public/assets/icons.ts
  public/assets/svg/SvgIcons.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/contexts/DarkModeContext.tsx
  src/store/useDarkModeStore.ts
  src/styles/globals.css
  src/types/utils.ts
  tailwind.config.ts
Labels: 🎨CSS, 🌟Feature, 🏭Refactor

#23 [#11] feat: 공통 컴포넌트(버튼) 제작
  src/app/page.tsx
  src/components/common/Button.tsx
  src/types/utils.ts
  tailwind.config.ts
Labels: 🌟Feature

#25 [#10] fix: 공통 컴포넌트(Dropdown) 수정
  package-lock.json
  package.json
  public/assets/svg/SvgIcons.tsx
  src/app/CommoneTest.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/contexts/DarkModeContext.tsx
  src/store/useDropdownStore.ts
  src/store/useVisibilityStore.ts
  src/types/utils.ts
  tailwind.config.ts
Labels: 🤬BugFix

#26 add: storybook 재설치
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
Labels: ⚙Setting

#27 chore: storybook 관련 설정 추가
  .storybook/main.ts
  .storybook/preview.ts
  src/components/common/Input.stories.ts
Labels: ⚙Setting

#28 fix: storybook staticDirs 경로 수정
  .storybook/main.ts
Labels: 🤬BugFix

#29 [#11] feat: 공통 컴포넌트 버튼들 Storybook 적용
  public/assets/svg/SvgIcons.tsx
  src/components/common/AskButton.stories.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Header.tsx
  src/components/common/Input.stories.ts
  src/components/common/TopButton.stories.tsx
  src/types/utils.ts
Labels: 🤬BugFix, 🌟Feature

#43 [#35] design: NewestTrend Section 컴포넌트 추가
  package-lock.json
  package.json
  public/assets/images/Warning.png
  public/assets/svg/SvgIcons.tsx
  src/app/(home)/_components/Card/Label.tsx
  src/app/(home)/_components/Card/ServiceCardsGrid.tsx
  src/app/(home)/_components/NewestTrendSection.tsx
  src/app/(home)/_components/SecureProcessSection.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Header.tsx
Labels: 🎨CSS, ⚙Setting

#49 [#42] feat: FindingFlaw Section 컴포넌트 제작
  public/assets/svg/SvgIcons.tsx
  src/app/(home)/_components/FindindFlawSection.tsx
  src/app/(home)/_components/HeroSection.tsx
  src/app/(home)/page.tsx
  src/components/common/AskButton.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/TopButton.stories.tsx
  src/components/common/TopButton.tsx
  src/styles/globals.css
  src/types/utils.ts
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#50 [#43] fix: FindingFlaw Section Text 애니메이션 적용
  src/app/(home)/_components/FindindFlawSection.tsx
Labels: 🎨CSS

#53 [#52] feat: Inquiry 기능 구현 및 테스트 코드 작성
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  public/assets/svg/SvgIcons.tsx
  src/__tests__/components/Inquiry.test.tsx
  src/__tests__/store/useInquiryStore.test.ts
  src/app/(home)/_components/HeroSection.tsx
  src/app/(home)/_components/Inquiry.tsx
  src/app/(home)/page.tsx
  src/app/api/contact/route.ts
  src/store/useInquiryStore.ts
  src/types/inquiry.d.ts
  tsconfig.json
Labels: 🚀API, 🌟Feature, ✅Test

#54 [#33] design: 랜딩페이지 전체 text, padding 등 조정
  src/app/(home)/_components/Card/ServiceCard.tsx
  src/app/(home)/_components/FindindFlawSection.tsx
  src/app/(home)/_components/HeroSection.tsx
  src/app/(home)/_components/Inquiry.tsx
  src/app/(home)/_components/NewestTrendSection.tsx
  src/app/(home)/_components/SecureProcessSection.tsx
  src/app/(home)/page.tsx
  src/components/common/Header.tsx
Labels: 🎨CSS

#57 [#47] feat: MY저장소 컴포넌트 추가
  next.config.mjs
  public/assets/svg/SvgIcons.tsx
  src/app/(home)/_components/FindindFlawSection.tsx
  src/app/(my-repo)/_components/KebobButton.tsx
  src/app/(my-repo)/_components/LibraryItem.tsx
  src/app/(my-repo)/_components/LibraryList.tsx
  src/app/(my-repo)/_components/LibraryToolbar.tsx
  src/app/(my-repo)/_components/RoundButton.tsx
  src/app/(my-repo)/_components/UserItem.tsx
  src/app/(my-repo)/_hook/usePagination.ts
  src/app/(my-repo)/me/clipping-articles/_components/ArticleList.tsx
  src/app/(my-repo)/me/clipping-articles/_components/ClippingArticle.tsx
  src/app/(my-repo)/me/clipping-articles/page.tsx
  src/app/(my-repo)/me/detected-files/_components/DetectedFile.tsx
  src/app/(my-repo)/me/detected-files/page.tsx
  src/app/(my-repo)/me/page.tsx
  src/app/(my-repo)/me/setting/_components/EmailToggle.tsx
  src/app/(my-repo)/me/setting/page.tsx
  src/app/(my-repo)/mylibrary/_components/RepositoryItem.tsx
  src/app/(my-repo)/mylibrary/page.tsx
  src/components/common/Footer.tsx
  src/components/common/PageTitle.tsx
  src/components/common/UserPic.tsx
  src/components/common/chips/AssistChips.tsx
  src/components/common/chips/SuggestionChips.tsx
  src/styles/globals.css
  src/types/repository.d.ts
  src/types/utils.d.ts
  tailwind.config.ts
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#59 [#45] feat: 취약점 분석 페이지 목업 구현
  public/assets/images/myRepository/bug.svg
  public/assets/images/myRepository/completed.svg
  public/assets/images/myRepository/inspection.svg
  public/assets/images/myRepository/listCaption.svg
  public/assets/images/myRepository/loader.svg
  public/assets/images/myRepository/noneFile.svg
  public/assets/images/myRepository/selectFile.svg
  src/app/(home)/_components/FindingFlawSection.tsx
  src/app/(home)/page.tsx
  src/app/analyze/[id]/_components/AnalyzeModal.tsx
  src/app/analyze/[id]/_components/CompletedFileViewer.tsx
  src/app/analyze/[id]/_components/FileList.tsx
  src/app/analyze/[id]/_components/FileListItem.tsx
  src/app/analyze/[id]/_components/FileTabs.tsx
  src/app/analyze/[id]/_components/FileViewer.tsx
  src/app/analyze/[id]/_components/Infobox.tsx
  src/app/analyze/[id]/_components/LoadingModal.tsx
  src/app/analyze/[id]/_components/ModifiedCode.tsx
  src/app/analyze/[id]/page.tsx
  src/app/chips/page.tsx
  src/components/common/Button.tsx
  src/components/common/PageTitle.tsx
  src/components/common/PcOnlyMessage.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/chips/InputChips.tsx
  src/store/useFileStore.ts
  src/stories/InputChips.stories.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨CSS, 🌟Feature, 🏭Refactor

#61 [#60] feat: 사용자 Github Repository fetch
  package-lock.json
  package.json
  src/app/(home)/_components/HeroSection.tsx
  src/app/(my-repo)/_components/LibraryList.tsx
  src/app/(my-repo)/me/detected-files/_components/DetectedFile.tsx
  src/app/(my-repo)/mylibrary/_components/RepositoryItem.tsx
  src/app/(my-repo)/mylibrary/page.tsx
  src/app/api-test/analyze/[owner]/[name]/_components/FileList.tsx
  src/app/api-test/analyze/[owner]/[name]/_components/FileListItem.tsx
  src/app/api-test/analyze/[owner]/[name]/page.tsx
  src/app/api-test/me/clip-article/page.tsx
  src/app/api-test/me/detected-list/page.tsx
  src/app/api-test/me/page.tsx
  src/app/api-test/me/setting/page.tsx
  src/app/api-test/mylibrary/_components/RepoList.tsx
  src/app/api-test/mylibrary/page.tsx
  src/app/api/github/contents/route.ts
  src/app/api/github/file/route.ts
  src/app/api/github/repositories/route.ts
  src/app/vulnerability-db/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/lib/api/github.ts
  src/lib/auth.ts
  src/store/useGithubStore.ts
  src/types/github-repos.d.ts
  src/types/index.d.ts
  src/types/next-auth.d.ts
  src/types/repository.d.ts
Labels: 🚀API

#62 [#58] MY저장소 페이지 퍼블리싱
  public/assets/svg/SvgIcons.tsx
  src/app/(my-repo)/_components/KebobButton.tsx
  src/app/(my-repo)/_components/LibraryItem.tsx
  src/app/(my-repo)/_components/LibraryList.tsx
  src/app/(my-repo)/_components/LibraryToolbar.tsx
  src/app/(my-repo)/_components/RoundButton.tsx
  src/app/(my-repo)/_components/UserItem.tsx
  src/app/(my-repo)/layout.tsx
  src/app/(my-repo)/me/clipping-articles/_components/ArticleList.tsx
  src/app/(my-repo)/me/clipping-articles/_components/ClippingArticle.tsx
  src/app/(my-repo)/me/clipping-articles/page.tsx
  src/app/(my-repo)/me/detected-files/_components/DetectedFile.tsx
  src/app/(my-repo)/me/detected-files/_components/DetectedList.tsx
  src/app/(my-repo)/me/detected-files/mock/detectedFiles.ts
  src/app/(my-repo)/me/detected-files/page.tsx
  src/app/(my-repo)/me/layout.tsx
  src/app/(my-repo)/me/page.tsx
  src/app/(my-repo)/me/setting/_components/EmailToggle.tsx
  src/app/(my-repo)/me/setting/page.tsx
  src/app/(my-repo)/mylibrary/_components/LibraryLogin.tsx
  src/app/(my-repo)/mylibrary/_components/LibraryTitle.tsx
  src/app/(my-repo)/mylibrary/_components/RepositoryList.tsx
  src/app/(my-repo)/mylibrary/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/PageTitle.tsx
  src/components/common/chips/AssistChips.tsx
Labels: 🎨CSS

#65 feat: 취약점DB 페이지 컴포넌트 추가
  package-lock.json
  package.json
  public/assets/images/vulnerability-db/CardImg1.png
  public/assets/images/vulnerability-db/CardImg2.png
  public/assets/images/vulnerability-db/CardImg3.png
  public/assets/svg/vulnerabilityDbSvg.tsx
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/_components/MainPostSection.tsx
  src/app/vulnerability-db/_components/Pagination.tsx
  src/app/vulnerability-db/_components/TopicList.tsx
  src/app/vulnerability-db/_components/VulnerabilityCard.tsx
  src/app/vulnerability-db/_components/VulnerabilityList.tsx
  src/app/vulnerability-db/_components/_data/postCardMock.ts
  src/app/vulnerability-db/_components/_data/topicListMock.ts
  src/app/vulnerability-db/_components/button/PinButton.tsx
  src/app/vulnerability-db/_components/button/ShareButton.tsx
  src/app/vulnerability-db/_components/button/TagButton.tsx
  src/app/vulnerability-db/_components/imageCard/ImageCardItem.tsx
  src/app/vulnerability-db/_components/imageCard/ImageCardList.tsx
  src/app/vulnerability-db/_components/mainPostCard/MainPostCardItem.tsx
  src/app/vulnerability-db/_components/mainPostCard/MainPostCardList.tsx
  src/app/vulnerability-db/_components/smallPostCard/SmallPostCardItem.tsx
  src/app/vulnerability-db/_components/smallPostCard/SmallPostCardList.tsx
  src/app/vulnerability-db/_utils/chipsLogic.ts
  src/app/vulnerability-db/_utils/formatDate.ts
  src/app/vulnerability-db/_utils/sortPostCard.ts
  src/app/vulnerability-db/layout.tsx
  src/app/vulnerability-db/page.tsx
  src/store/usePaginationStore.ts
  src/store/useSortStore.ts
  src/types/index.d.ts
  src/types/pagination.d.ts
  src/types/postCardTypes.d.ts
  src/types/vulnerability-db-sort.d.ts
Labels: 🎨CSS, 🌟Feature

#66 rename: 변경된 기획 routing 적용
  src/app/(my-repo)/layout.tsx
  src/app/(my-repo)/me/detected-files/_components/DetectedFile.tsx
  src/app/(my-repo)/me/detected-files/mock/detectedFiles.ts
  src/app/(my-repo)/me/detected-files/page.tsx
  src/app/(my-repo)/mylibrary/_components/RepositoryList.tsx
  src/app/me/layout.tsx
  src/app/me/page.tsx
  src/app/me/scraps/_components/ArticleList.tsx
  src/app/me/scraps/_components/ClippingArticle.tsx
  src/app/me/scraps/page.tsx
  src/app/me/setting/_components/EmailToggle.tsx
  src/app/me/setting/page.tsx
  src/app/repos/[id]/_components/AnalyzeModal.tsx
  src/app/repos/[id]/_components/CompletedFileViewer.tsx
  src/app/repos/[id]/_components/FileList.tsx
  src/app/repos/[id]/_components/FileListItem.tsx
  src/app/repos/[id]/_components/FileTabs.tsx
  src/app/repos/[id]/_components/FileViewer.tsx
  src/app/repos/[id]/_components/Infobox.tsx
  src/app/repos/[id]/_components/LoadingModal.tsx
  src/app/repos/[id]/_components/ModifiedCode.tsx
  src/app/repos/[id]/page.tsx
  src/app/repos/_components/KebobButton.tsx
  src/app/repos/_components/LibraryItem.tsx
  src/app/repos/_components/LibraryLogin.tsx
  src/app/repos/_components/LibraryTitle.tsx
  src/app/repos/_components/LibraryToolbar.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/app/repos/_components/RoundButton.tsx
  src/app/repos/_hook/usePagination.ts
  src/app/repos/page.tsx
  src/app/vuldb/_components/MainPostSection.tsx
  src/app/vuldb/_components/Pagination.tsx
  src/app/vuldb/_components/TopicList.tsx
  src/app/vuldb/_components/_data/postCardMock.ts
  src/app/vuldb/_components/_data/topicListMock.ts
  src/app/vuldb/_components/button/PinButton.tsx
  src/app/vuldb/_components/button/ShareButton.tsx
  src/app/vuldb/_components/button/TagButton.tsx
  src/app/vuldb/_components/imageCard/ImageCardItem.tsx
  src/app/vuldb/_components/imageCard/ImageCardList.tsx
  src/app/vuldb/_components/mainPostCard/MainPostCardItem.tsx
  src/app/vuldb/_components/mainPostCard/MainPostCardList.tsx
  src/app/vuldb/_components/smallPostCard/SmallPostCardItem.tsx
  src/app/vuldb/_components/smallPostCard/SmallPostCardList.tsx
  src/app/vuldb/_utils/chipsLogic.ts
  src/app/vuldb/_utils/formatDate.ts
  src/app/vuldb/_utils/sortPostCard.ts
  src/app/vuldb/items/[id]/page.tsx
  src/app/vuldb/page.tsx
  src/components/common/UserItem.tsx
Labels: ⚙Setting
