Repository hyeonji1125/sfacspace-06-project, pull requests merged in 2024-09, with the labels that each got.

#72 [#71] 취약점 분석 페이지 UI 구현
  public/assets/images/myRepository/bug.svg
  public/assets/images/myRepository/inspection.svg
  public/assets/images/myRepository/loader.svg
  public/assets/images/myRepository/noneFile.svg
  src/app/repos/[id]/_components/CompletedFileViewer.tsx
  src/app/repos/[id]/_components/FileList.tsx
  src/app/repos/[id]/_components/FileListItem.tsx
  src/app/repos/[id]/_components/FileTabs.tsx
  src/app/repos/[id]/_components/FileViewer.tsx
  src/app/repos/[id]/_components/Infobox.tsx
  src/app/repos/[id]/_components/LoadingModal.tsx
  src/app/repos/[id]/page.tsx
  src/app/repos/[owner]/[name]/_components/AnalyzeModal.tsx
  src/app/repos/[owner]/[name]/_components/BreadCrumb.tsx
  src/app/repos/[owner]/[name]/_components/FileDropdown.tsx
  src/app/repos/[owner]/[name]/_components/FileInspectionProgress.tsx
  src/app/repos/[owner]/[name]/_components/FileList.tsx
  src/app/repos/[owner]/[name]/_components/FileListItem.tsx
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/_components/ModifiedCode.tsx
  src/app/repos/[owner]/[name]/_components/ReposTitle.tsx
  src/app/repos/[owner]/[name]/layout.tsx
  src/app/repos/[owner]/[name]/page.tsx
  src/app/repos/[owner]/[name]/repo_inspection/page.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/components/common/Button.tsx
  src/components/common/ProgressBar.tsx
  src/store/useGithubStore.ts
  src/types/github-repos.d.ts
  tailwind.config.ts
Labels: 🚀API, 🎨CSS, 🌟Feature

#73 [#70] feat: repos 하위 페이지 수정 및 기능 추가
  public/assets/svg/SvgIcons.tsx
  src/app/(home)/_components/Inquiry.tsx
  src/app/me/(me-layout)/layout.tsx
  src/app/me/(me-layout)/scraps/_components/ArticleList.tsx
  src/app/me/(me-layout)/scraps/_components/ClippingArticle.tsx
  src/app/me/(me-layout)/scraps/page.tsx
  src/app/me/(me-layout)/setting/_components/EmailToggle.tsx
  src/app/me/(me-layout)/setting/page.tsx
  src/app/me/_constants/profileLinks.ts
  src/app/me/contact/page.tsx
  src/app/me/page.tsx
  src/app/me/scraps/_components/ArticleList.tsx
  src/app/me/setting/page.tsx
  src/app/repos/_components/BookmarkButton.tsx
  src/app/repos/_components/DetectLink.tsx
  src/app/repos/_components/KebobButton.tsx
  src/app/repos/_components/LibraryItem.tsx
  src/app/repos/_components/LibraryToolbar.tsx
  src/app/repos/_components/LogoutComfirmModal.tsx
  src/app/repos/_components/ReposFilterButtons.tsx
  src/app/repos/_components/ReposToolbar.tsx
  src/app/repos/_components/RepositoryChip.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/app/repos/_components/RoundButton.tsx
  src/app/repos/_components/UserItemWithLogout.tsx
  src/app/repos/_hook/usePagination.ts
  src/app/repos/_utils/filterRepos.ts
  src/app/repos/page.tsx
  src/app/vuldb/_components/Pagination.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/common/PageTitle.tsx
  src/components/common/UserItem.tsx
  src/components/common/UserPic.tsx
  src/hooks/useFilterItems.ts
  src/store/useGithubStore.ts
  src/store/useLibraryStore.ts
  src/store/usePaginationStore.ts
  src/stories/Dropdown.stories.tsx
  src/types/github-repos.d.ts
  src/types/library.d.ts
  src/types/pagination.d.ts
  src/types/utils.d.ts
  src/utils/debounce.ts
  src/utils/sortItems.ts
Labels: 🎨CSS, 🌟Feature

#75 [#48] feat: 취약점DB페이지 컴포넌트 추가 및 퍼블리싱
  crawling.js
  package-lock.json
  package.json
  public/assets/svg/vulnerabilityDbSvg.tsx
  src/app/vuldb/_components/SearchBar.tsx
  src/app/vuldb/_components/TopicList.tsx
  src/app/vuldb/_components/imageCard/ImageCardItem.tsx
  src/app/vuldb/_components/imageCard/ImageCardList.tsx
  src/app/vuldb/_components/mainPostCard/MainPostCardItem.tsx
  src/app/vuldb/_components/mainPostCard/MainPostCardList.tsx
  src/app/vuldb/_components/smallPostCard/SmallPostCardItem.tsx
  src/app/vuldb/_components/smallPostCard/SmallPostCardList.tsx
  src/app/vuldb/items/[id]/_components/DetailHeader.tsx
  src/app/vuldb/items/[id]/_components/DetailMainSection.tsx
  src/app/vuldb/items/[id]/page.tsx
  src/app/vuldb/page.tsx
Labels: 🎨CSS, 🌟Feature

#78 [#76] feat: llama3 연결 및 테스트 작업
  public/assets/images/vulnerability-db/items/CardImg1.png
  public/assets/images/vulnerability-db/items/CardImg2.png
  public/assets/images/vulnerability-db/items/CardImg3.png
  src/app/(home)/_components/HeroSection.tsx
  src/app/api-test/mylibrary/page.tsx
  src/app/api/llama3/route.ts
  src/app/layout.tsx
  src/app/login/_components/Login.tsx
  src/app/providers.tsx
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/_components/DetectLink.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/app/repos/page.tsx
  src/components/common/Header.tsx
  src/lib/auth.ts
  src/lib/customAuth.ts
  src/lib/llama3.ts
  src/store/useGithubStore.ts
  src/types/github-repos.d.ts
Labels: 🚀API, ✅Test

#81 [#80] refact: 유저 정보 비동기 처리로 수정 및 vuldb 이미지 경로 수정
  public/assets/images/vuldb/items/CardImg1.png
  public/assets/images/vuldb/items/CardImg2.png
  public/assets/images/vuldb/items/CardImg3.png
  src/app/api-test/analyze/[owner]/[name]/_components/FileList.tsx
  src/app/api-test/analyze/[owner]/[name]/_components/FileListItem.tsx
  src/app/api-test/analyze/[owner]/[name]/page.tsx
  src/app/api-test/me/clip-article/page.tsx
  src/app/api-test/me/detected-list/page.tsx
  src/app/api-test/me/page.tsx
  src/app/api-test/me/setting/page.tsx
  src/app/api-test/mylibrary/_components/RepoList.tsx
  src/app/api-test/mylibrary/page.tsx
  src/app/data-practice/page.tsx
  src/app/vuldb/_components/imageCard/ImageCardItem.tsx
  src/lib/auth.ts
  src/lib/customAuth.ts
Labels: 🤬BugFix, 🖥Deploy, 🏭Refactor

#83 Dev -> Main
  public/assets/images/vuldb/items/CardImg1.png
  public/assets/images/vuldb/items/CardImg2.png
  public/assets/images/vuldb/items/CardImg3.png
  src/app/api-test/analyze/[owner]/[name]/_components/FileList.tsx
  src/app/api-test/analyze/[owner]/[name]/_components/FileListItem.tsx
  src/app/api-test/analyze/[owner]/[name]/page.tsx
  src/app/api-test/me/clip-article/page.tsx
  src/app/api-test/me/detected-list/page.tsx
  src/app/api-test/me/page.tsx
  src/app/api-test/me/setting/page.tsx
  src/app/api-test/mylibrary/_components/RepoList.tsx
  src/app/api-test/mylibrary/page.tsx
  src/app/data-practice/page.tsx
  src/app/vuldb/_components/imageCard/ImageCardItem.tsx
  src/lib/auth.ts
  src/lib/customAuth.ts
Labels: 🤬BugFix, 🖥Deploy

#84 [#68]nist page 게시물 20개 크롤링 기능구현완료
  package-lock.json
  src/lib/crawling/formatDate.js
  src/lib/crawling/nist.js
  src/lib/firebase.js
  src/lib/firebase.ts
  tsconfig.json
Labels: 🚀API, Backend, 🌟Feature

#86 [#70] fix: repos 페이지 db 및 filter 로직 수정, 리팩토링
  src/app/repos/_components/BookmarkButton.tsx
  src/app/repos/_components/DetectLink.tsx
  src/app/repos/_components/LogoutConfirmModal.tsx
  src/app/repos/_components/ReposFilterButtons.tsx
  src/app/repos/_components/ReposToolbar.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/app/repos/_components/UserItemWithLogout.tsx
  src/app/repos/_utils/fetchRepos.ts
  src/app/repos/_utils/filterRepos.ts
  src/app/repos/_utils/findMatchData.ts
  src/components/common/Header.tsx
  src/components/common/UserItem.tsx
  src/hooks/fetchData.ts
  src/hooks/useFilterItems.ts
  src/hooks/useGetUser.ts
  src/lib/customAuth.ts
  src/store/useGithubStore.ts
  src/store/useLibraryStore.ts
  src/types/github-repos.d.ts
  src/types/library.d.ts
Labels: 🚀API, 🤬BugFix, 🌟Feature, 🏭Refactor

#92 [#71] 취약점 검사 페이지 UI 변경 사항 적용 + 기능 구현
  package-lock.json
  package.json
  src/app/repos/[owner]/[name]/_components/AnalyzeModal.tsx
  src/app/repos/[owner]/[name]/_components/BreadCrumb.tsx
  src/app/repos/[owner]/[name]/_components/FileDropdown.tsx
  src/app/repos/[owner]/[name]/_components/FileInspectionProgress.tsx
  src/app/repos/[owner]/[name]/_components/FileItem.tsx
  src/app/repos/[owner]/[name]/_components/FileList.tsx
  src/app/repos/[owner]/[name]/_components/FileListContent.tsx
  src/app/repos/[owner]/[name]/_components/FileListLoading.tsx
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/_components/FileViewerLoading.tsx
  src/app/repos/[owner]/[name]/_components/InspectionAlert.tsx
  src/app/repos/[owner]/[name]/_components/ModifiedCode.tsx
  src/app/repos/[owner]/[name]/_utils/getSelectedItems.ts
  src/app/repos/[owner]/[name]/_utils/useIsPathResult.ts
  src/app/repos/[owner]/[name]/_utils/useRepoParams.ts
  src/app/repos/[owner]/[name]/page.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/ModifiedCode.tsx
  src/app/repos/[owner]/[name]/repo_inspection/page.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/store/useGithubStore.ts
  src/styles/code.css
  src/styles/globals.css
  src/types/github-repos.d.ts
  tailwind.config.ts
Labels: 🎨CSS, 🌟Feature, 🏭Refactor

#98 [#96] feat: llama3 연동 및 결과 출력 -> firestore 결과 저장
  package-lock.json
  package.json
  src/app/api/github/commits/route.ts
  src/app/api/github/contents/route.ts
  src/app/api/github/file/route.ts
  src/app/api/github/repositories/route.ts
  src/app/api/llama3/route.ts
  src/app/repos/[owner]/[name]/_components/AnalyzeModal.tsx
  src/app/repos/[owner]/[name]/_components/FileItem.tsx
  src/app/repos/[owner]/[name]/_components/FileList.tsx
  src/app/repos/[owner]/[name]/_components/FileListContent.tsx
  src/app/repos/[owner]/[name]/page.tsx
  src/components/common/Header.tsx
  src/hooks/fetchData.ts
  src/lib/api/github.ts
  src/lib/llama3.ts
  src/store/useGithubStore.ts
  src/store/useLlama3Store.ts
  src/types/github-repos.d.ts
  src/types/index.d.ts
  src/types/llama3.d.ts
Labels: 🚀API, Backend

#99 [#27] feat: 취약점 분석 페이지 Infobox 구현
  package-lock.json
  package.json
  src/app/repos/[owner]/[name]/_components/FileList.tsx
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/_components/InspectionAlert.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/Infobox.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/InspectionResult.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/ModifiedCode.tsx
  src/app/repos/[owner]/[name]/repo_inspection/page.tsx
  src/lib/api/github.ts
  src/styles/globals.css
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#100 [#27] feat: 분석 결과 페이지 구현
  src/app/repos/[owner]/[name]/_components/AnalyzeModal.tsx
  src/app/repos/[owner]/[name]/_components/FileItem.tsx
  src/app/repos/[owner]/[name]/_components/FileList.tsx
  src/app/repos/[owner]/[name]/_components/FileListContent.tsx
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/_components/InspectionAlert.tsx
  src/app/repos/[owner]/[name]/page.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/Infobox.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/InspectionResult.tsx
  src/app/repos/[owner]/[name]/repo_inspection/page.tsx
  src/components/common/Header.tsx
  src/types/github-repos.d.ts
  src/types/llama3.d.ts
Labels: 🌟Feature

#101 fix: repos, me 하위 페이지 일부 수정
  src/app/me/(me-layout)/scraps/_components/ArticleList.tsx
  src/app/me/(me-layout)/scraps/_components/ClippingArticle.tsx
  src/app/me/(me-layout)/scraps/_components/LoadingArticles.tsx
  src/app/repos/_components/BookmarkButton.tsx
  src/app/repos/_components/LoadingRepo.tsx
  src/app/repos/_components/ReposFilterButtons.tsx
  src/app/repos/_components/ReposLibrary.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/app/repos/page.tsx
  src/app/vuldb/_components/Pagination.tsx
  src/components/common/LoadingBox.tsx
  src/components/common/chips/SuggestionChips.tsx
  src/hooks/useFilterItems.ts
  src/store/useLibraryStore.ts
  src/types/chips.d.ts
  src/types/library.d.ts
  src/utils/sortItems.ts
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#103 중간 발표 전 테스트
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/InspectionResult.tsx
  src/lib/api/github.ts
  src/store/useLlama3Store.ts
  src/types/llama3.d.ts
  src/utils/getLineNumber.ts
Labels: 🚀API, Backend

#105 fix: 정규식 수정
  src/lib/llama3.ts
Labels: 🚀API

#109 [#108] fix: repos, scraps 기능 및 디자인 수정사항 반영, 스켈레톤 적용
  public/assets/svg/SvgIcons.tsx
  src/app/me/(me-layout)/scraps/_components/ArticleLibrary.tsx
  src/app/me/(me-layout)/scraps/_components/ArticleList.tsx
  src/app/me/(me-layout)/scraps/_components/ClippingArticle.tsx
  src/app/me/(me-layout)/scraps/_components/LoadingArticles.tsx
  src/app/me/(me-layout)/scraps/page.tsx
  src/app/repos/_components/BookmarkButton.tsx
  src/app/repos/_components/LibraryLogin.tsx
  src/app/repos/_components/LibraryTitle.tsx
  src/app/repos/_components/LibraryToolbar.tsx
  src/app/repos/_components/ReposLibrary.tsx
  src/app/repos/_components/RepositoryItem.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/components/common/Dropdown.tsx
  src/components/common/EmptyContent.tsx
  src/components/common/UserItem.tsx
  src/hooks/useFilterItems.ts
  src/lib/scrapPost.ts
  src/store/useScrapStore.ts
  src/types/scrap.d.ts
  src/utils/sortItems.ts
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#110 [#87] 챗봇 컴포넌트 생성 및 LLM API 연결
  package-lock.json
  package.json
  public/assets/svg/SvgIcons.tsx
  src/app/api/ai-chat/route.ts
  src/app/vuldb/items/[id]/page.tsx
  src/components/common/AskButton.tsx
  src/components/common/chatbot/ChatBubble.tsx
  src/components/common/chatbot/ChatContainer.tsx
  src/components/common/chatbot/ChatInput.tsx
  src/components/common/chatbot/ChatLog.tsx
  src/components/common/chatbot/FlawDetectorChat.tsx
  src/lib/llama3.ts
  src/store/useChatbotStore.ts
  src/types/chatbot.d.ts
Labels: 🚀API, 🎨CSS, 🌟Feature

#111 [#71] fix: 취약점 분석 페이지 배포 에러 수정
  next.config.mjs
  src/app/repos/[owner]/[name]/_components/FileListContent.tsx
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/page.tsx
Labels: 🤬BugFix

#113 [#112] contact validation/modal
  src/app/(home)/_components/Inquiry.tsx
  src/components/common/Modal.tsx
  src/components/common/contact/ContactForm.tsx
  src/components/common/contact/SubmitContactFormModal.tsx
  src/store/useInquiryStore.ts
  src/types/inquiry.d.ts
  src/utils/validateForm.ts
Labels: 🤬BugFix, 🎨CSS, 🌟Feature

#115 [#112] auth middleware 추가
  src/middleware.ts
Labels: 🌟Feature

#117 feat: 공통 404, error 페이지 추가, 챗봇 기능 수정, me 페이지 하위 다크모드 색상 변경, 유저 데이터 삭제 로직 추가
  public/assets/svg/SvgIcons.tsx
  src/app/(home)/page.tsx
  src/app/api/user/route.ts
  src/app/error.tsx
  src/app/me/(me-layout)/layout.tsx
  src/app/me/contact/page.tsx
  src/app/me/page.tsx
  src/app/not-found.tsx
  src/app/repos/_components/DetectLink.tsx
  src/app/repos/_components/LibraryLogin.tsx
  src/app/repos/_components/LibraryTitle.tsx
  src/app/repos/_components/LogoutConfirmModal.tsx
  src/app/repos/_components/UserItemWithLogout.tsx
  src/app/repos/page.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/common/PageTitle.tsx
  src/components/common/PcOnlyMessage.tsx
  src/components/common/chatbot/ChatBubble.tsx
  src/components/common/chatbot/ChatContainer.tsx
  src/components/common/chatbot/ChatInput.tsx
  src/components/common/chatbot/FlawDetectorChat.tsx
  src/lib/customAuth.ts
  src/store/useChatbotStore.ts
  src/utils/deleteUserData.ts
Labels: 🚀API, 🤬BugFix, 🎨CSS, 🌟Feature

#118 design: 다크모드 수정(특정 페이지), 챗봇 위치 수정
  public/assets/images/flaw-detector-main-logo.svg
  public/assets/svg/SvgIcons.tsx
  src/app/(home)/_components/FindingFlawSection.tsx
  src/app/(home)/_components/HeroSection.tsx
  src/app/(home)/_components/Inquiry.tsx
  src/app/(home)/_components/NewestTrendSection.tsx
  src/app/(home)/_components/SecureProcessSection.tsx
  src/app/login/_components/Login.tsx
  src/app/login/page.tsx
  src/app/repos/_components/LibraryLogin.tsx
  src/app/repos/_components/LogoutConfirmModal.tsx
  src/app/vuldb/_components/Pagination.tsx
  src/components/common/AskButton.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/Textarea.tsx
  src/components/common/TopButton.tsx
  src/components/common/WaveCircle.tsx
  src/components/common/chatbot/ChatContainer.tsx
  src/components/common/chatbot/ChatLog.tsx
  src/components/common/contact/ContactForm.tsx
  tailwind.config.ts
Labels: 🤬BugFix, 🎨CSS

#119 fix: css 일부 수정, hero 섹션 스크롤다운 버튼 위치 수정
  src/app/(home)/_components/HeroSection.tsx
  src/app/login/page.tsx
  src/components/common/Header.tsx
  src/components/common/PcOnlyMessage.tsx
  src/components/common/chatbot/ChatContainer.tsx
Labels: 🤬BugFix, 🎨CSS

#121 [#120] feat: 취약점 발견된 부분 동적 생성 및 위치보기 구현
  src/app/api/llama3/route.ts
  src/app/repos/[owner]/[name]/_components/FileViewer.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/Infobox.tsx
  src/app/repos/[owner]/[name]/repo_inspection/_components/InspectionResult.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/lib/llama3.ts
  src/store/useGithubStore.ts
  src/store/useLlama3Store.ts
  src/types/llama3.d.ts
  src/utils/getLineNumber.ts
Labels: 🌟Feature
